version: '3.8'

services:
  api_service:
    build: ./api_service
    ports:
      - "5004:5004"
    env_file:
      - ./api_service/.env
    environment:
      - ROUTE_SERVICE_URL=http://route_service:8001/calculate
    depends_on:
      - route_service
    restart: unless-stopped

  route_service:
    build: ./route_service
    ports:
      - "8001:8001"
    restart: unless-stopped
